### ISSUE TITLE
Investigate how we can exclude Travis for specific templates

### ISSUE THREAD

**Issue by renatocaval** [playframework/templatecontrol#99]
The copy of travis files is being disable on this PR #98 becasue it breaks
https://github.com/playframework/play-scala-secure-session-example and https://github.com/playframework/play-webgoat that a more specific travis setup.

**Comment by dwijnand** [comment]
In play-scala-secure-session-example's case it requires libsodium-dev apt-get installed.  play-webgoat doesn't have a gradle build.

https://github.com/playframework/playframework.com is another one: I hand-rolled it's .travis.yml after bootstrapping from the one templatecontrol suggested.  It also doesn't have a gradle build, it also doesn't need jabba/adoptopenjdk, it also has to setup a mysql database and clone a repo.  It could do that in scripts in `scripts/`, so it could be worked around (unless scripts runs in a less priviledge'd mode to `before_script`?

The better solution, IMO, is for the .travis.yml changes to be YAML rewrites instead of file overrides or sed-rewrites.

**Comment by renatocaval** [comment]
playframework.com is not managed by template control

**Comment by dwijnand** [comment]
That's right: https://github.com/lightbend/templatecontrol/issues/91

**Comment by dwijnand** [comment]
Now that we model the projects in code we should be able to resolve this more easily.
